namespace backend.Models
{
    public enum OptionSource
    {
        Manual,      // added by normal participant
        Generated,   // generated by system
        System       // created by organizator
    }
    /// <summary>
    /// Represents a specific place and time option for an event.
    /// Users can vote on these options during the voting phase.
    /// </summary>
    public class EventOption
    {
        public Guid Id { get; set; }
        public Guid EventId { get; set; }
        public Guid? CreatedByUserId { get; set; }
        public OptionSource Source { get; set; }
        public required string PlaceName { get; set; }
        public string? Address { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public required DateTimeOffset TimeFrom { get; set; }
        public required DateTimeOffset TimeTo { get; set; }
        public bool IsSelected { get; set; } = false; // Final choice
        // navigation
        public ICollection<Vote> Votes { get; set; } = new List<Vote>();
    }

}
